version: 2.1
orbs:
  node: circleci/node@4.1.0
jobs:

  test:
    executor:
      name: node/default
      tag: '13.14'
    steps:
      - checkout
      - node/install-packages
      - run:
          command: cd frontend && npm install && npm run test
          
  #build:
    #...
  deployProduction:
    machine:
      enabled: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "29:b0:81:51:1d:74:07:22:fd:e6:92:7c:62:21:e3:66"
            - "3f:5e:58:fe:85:64:5b:89:1f:5c:d2:cd:3f:b4:06:c2"
      - run:
          name: Deploy Over SSH 
          command: |
             ssh $SSH_USER@$SSH_HOST "cd CI-CD && git stash && git pull && echo \"const IP = '$SSH_HOST'; export default IP;\" > ./frontend/src/URL.js && echo \"const _ENV = 'prod'; export default _ENV;\" > ./frontend/src/ENV.js && echo \"module.exports = { env_2: 'prod' }\" > ./routes/ENV_2.js && npm run deployProd && pm2 restart server"
      - run:
          name: Deploy Over SSH 2
          command: |
             ssh $SSH_USER@$SSH_HOST_2 "cd CI-CD && git stash && git pull && echo \"const IP = '$SSH_HOST_2'; export default IP;\" > ./frontend/src/URL.js  && echo \"const _ENV = 'prod'; export default _ENV;\" > ./frontend/src/ENV.js  && echo \"module.exports = { env_2: 'prod' }\" > ./routes/ENV_2.js && npm run deployProd && pm2 restart server"

  deployDevelop:
    machine:
      enabled: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "5e:01:c4:15:7e:d9:47:7b:db:0b:f6:e3:4f:5f:36:a0"
      - run:
          name: Deploy Over SSH
          command: |
             ssh $SSH_USER@$SSH_HOST_3 "cd CI-CD && git stash && git pull && echo \"const IP = '$SSH_HOST_3'; export default IP;\" > ./frontend/src/URL.js && echo \"const _ENV = 'dev'; export default _ENV;\" > ./frontend/src/ENV.js && echo \"module.exports = { env_2: 'dev' }\" > ./routes/ENV_2.js && npm run deployDev && pm2 restart server"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      #- build
      - request-testing:
          type: approval
          requires:
            - test
      - deployProduction:
          #requires:
          #  - build # only deploy once build job has completedalol
          filters:
            branches:
              only: master # only deploy on the master branch
      - deployDevelop:
          #requires:
          #  - build # only deploy once build job has completed
          requires:
            - request-testing
          filters:
            branches:
              only: develop # only deploy on the develop branch
